### ISSUE TITLE
Errors while executing collector.py

### ISSUE THREAD

**Issue by ghost** [marcin-kolda/gcp-iam-collector#3]
Hello SIr , 

i ran the collector.py python script it is showing below errors , but in our gcp i want to fetch all the projects running under one folder  gcp setup is it possible to do ?

**Comment by ghost** [comment]
PS C:\Gcp_Python_Script\gcp-iam-collector-master> python collector.py
2021-10-15 09:08:58,842 INFO  __init__.py  file_cache is only supported with oauth2client<4.0.0
2021-10-15 09:08:58,855 INFO  __init__.py  file_cache is only supported with oauth2client<4.0.0
2021-10-15 09:08:58,887 INFO  __init__.py  file_cache is only supported with oauth2client<4.0.0
2021-10-15 09:08:58,895 INFO  __init__.py  file_cache is only supported with oauth2client<4.0.0
2021-10-15 09:08:58,911 DEBUG discovery.py URL being requested: GET https://cloudresourcemanager.googleapis.com/v1/projects?pageSize=400&alt=json
2021-10-15 09:08:58,919 INFO  transport.py Attempting refresh to obtain initial access_token
2021-10-15 09:08:58,919 INFO  client.py    Refreshing access_token
2021-10-15 09:09:01,937 INFO  collector.py parsing project [0] projectId: pj-becfr-eagle-dm-bi-prod
Traceback (most recent call last):
  File "C:\Gcp_Python_Script\gcp-iam-collector-master\collector.py", line 113, in <module>
    dump_projects(iam_iterator)
  File "C:\Gcp_Python_Script\gcp-iam-collector-master\collector.py", line 19, in dump_projects
    writer.writerow([project_id, project['projectNumber'],
TypeError: a bytes-like object is required, not 'str'

**Comment by darbyhopkins** [comment]
I ran into this same issue. Used this to fix it:
https://stackoverflow.com/questions/34283178/typeerror-a-bytes-like-object-is-required-not-str-in-python-and-csv
